### ISSUE TITLE
Class Command\ObjectCommand not found

### ISSUE THREAD

**Issue by ntaylor-86** [RamyTalal/Label-Printer#11]
Just did a fresh install with Composer

```
$ composer require RamyTalal/Label-Printer
```

And followed the **Template** instruction on the README.md
And that results in the error `Class Command\ObjectCommand not found`
Looking at the commit history `Object.php` was renamed to `ObjectCommand.php` - https://github.com/RamyTalal/Label-Printer/commit/f6150f19719217d42b0655490b7c93f98f1df7eb

To fix this issue I had to rename `Object.php` to `ObjectCommand.php` and changed the class name to `ObjectCommand`
After doing that this package worked a treat! 🎉

Is composer pulling down an old version?

Thanks for this package @RamyTalal

**Comment by RamyTalal** [comment]
Can you provide more information please?

**Comment by ntaylor-86** [comment]
Sorry RamyTalal. I accidentally hit the {enter}  key and it submitted my issue half way through typing the Title 😌

**Comment by RamyTalal** [comment]
Do you have the newest version? See https://github.com/RamyTalal/Label-Printer/tree/master/src/Command. The class is already named `ObjectCommand`, same for the file.

**Comment by ntaylor-86** [comment]
I followed the README and used Composer to install the package.
The version Composer installs must be out of date?

If anybody in the future installs via Composer and follows the README they will get the same `Class 'Command\ObjectCommand' not found` error.

I can confirm this package works great with the Brother QL-810W 👍 Thanks

**Comment by RamyTalal** [comment]
I think I forgot to make a new release. Can you check again?

**Comment by ntaylor-86** [comment]
Thanks @RamyTalal Composer is now pulling down the updated package with the renamed Class.
Issue solved.
