### ISSUE TITLE
Does not work "Cut" on QL 810w

### ISSUE THREAD

**Issue by kmlpandey77** [RamyTalal/Label-Printer#13]
I have use QL-810w, but "CUT " Function does not work. It's cut at last.
```php
$printer->addCommand(new Command\Text('Hallo'));
$printer->addCommand(new Command\Cut(Command\Cut::FULL));  
$printer->addCommand(new Command\Text('Hallo 2'));
$printer->addCommand(new Command\Cut(Command\Cut::FULL));
````

**Comment by ntaylor-86** [comment]
You are right @kmlpandey77 

I tried what you have in your initial comment and any Text that is added gets printed on the same label.

( Initially test on the left hand side. )
![bart_lisa_maggie](https://user-images.githubusercontent.com/28693782/87638632-72dfbf80-c787-11ea-93a5-23e785c2b23f.jpg)

I wrote a `flushCommands()` method that empties the `$command` array. So you are able to do something like this.

```
$labels = ['Bart', 'Lisa', 'Maggie'];

foreach ($labels as $label) {
    $printer->addCommand(new Command\Text( $label ));
    $printer->printLabel();
    $printer->flushCommands();
}
```

Which resulted in the labels on the right hand side of my image.

I'm sure @RamyTalal has a better solution for us than my `flushCommands()` method?

**Comment by RamyTalal** [comment]
I think it's nicer to flush in the `printLabel()` method.

**Comment by ntaylor-86** [comment]
That's even better!

**Comment by kmlpandey77** [comment]
Thank you @ntaylor-86,

I dont get `flushCommands()` method.

but I get a solution for now, (Using dash [------])
![image](https://user-images.githubusercontent.com/16485204/87689016-708d5d80-c7a7-11ea-8cab-eb850fb777c1.png)

```php
$printer->addCommand(new Command\Text("Order No: " . $sale->getOrderNumber() . "\n"));
foreach ($sale->items as $item) {  //$sale->item is food list
    for ($i=0; $item->qty > $i; $i++) {
        $printer->addCommand(new Command\Text("----------------\n"));  // love to use CUT::HALF or CUT:: CNAIN instead of dash [-----]
        $printer->addCommand(new Command\Text($item->item_title . "\n"));
    }
}
$printer->printLabel();
```

**Comment by ntaylor-86** [comment]
@kmlpandey77 from your photo, is your end goal is to have 6 different labels?

**Comment by ntaylor-86** [comment]
> I have use QL-810w, but "CUT " Function does not work. It's cut at last.
> 
> ```
> $printer->addCommand(new Command\Text('Hallo'));
> $printer->addCommand(new Command\Cut(Command\Cut::FULL));  
> $printer->addCommand(new Command\Text('Hallo 2'));
> $printer->addCommand(new Command\Cut(Command\Cut::FULL));
> ```

@RamyTalal is the Cut command meant to work how @kmlpandey77 has implemented there?
Does that work on your printer? Thanks.

**Comment by RamyTalal** [comment]
@ntaylor-86 That works.

**Comment by mgjuhler** [comment]
> flushCommands

@ntaylor-86 can you share the content of your  flushCommands ?

**Comment by ntaylor-86** [comment]
> > flushCommands
> 
> @ntaylor-86 can you share the content of your flushCommands ?

LoL. It's been two and a half years since I looked at this. I don't remember off the top of my head, but when I get a second I'll check it out.

**Comment by ntaylor-86** [comment]
@mgjuhler 

You can see the command implemented in this commit: https://github.com/ntaylor-86/RamyTalal-Label-Printer/commit/838973b920623612e766f44bc27a42a8fa9e7566
