### ISSUE TITLE
QL-720NW: disable auto cut

### ISSUE THREAD

**Issue by mgjuhler** [RamyTalal/Label-Printer#18]
I need to turn off auto cut on my QL-720NW when I print a series of labels.
I have tried with FULL, HALF, CHAIN and SPECIAL but none of them have worked.
Is there a way I can turn auto cutting off?

**Comment by RamyTalal** [comment]
I think it's possible, but I haven't implemented that functionality.

**Comment by ntaylor-86** [comment]
I've created a new class `DisableCut()` that allows you to disable the auto cut feature on the printer.

**Example**

```
$printer->addCommand(new Command\DisableCut());
$printer->addCommand(new Command\Text('Cut Disabled!'));
$printer->printLabel();
```

**The New Class**

Label-Printer/src/Command/DisableCut.php

```
<?php

namespace Talal\LabelPrinter\Command;

class DisableCut implements CommandInterface
{
    /**
     * @inheritdoc
     */
    public function read()
    {
        return chr(27) . 'iC' . chr(48);
    }
}

```

I have tested the `DisableCut()` command on a `QL-810W` with success. The commands seem to be the same between the `QL-720` and the `QL-810`

I can create a pull request for both `DisableCut()` and `EnableCut()` commands if you would like @RamyTalal ?

**Comment by ntaylor-86** [comment]
Hi @mgjuhler, the AutoCut command has been merged into the master branch.
An example is available now in the `README` >> [AutoCut Feature](https://github.com/RamyTalal/Label-Printer#autocut-feature)

`v1.0.2` with the new command is now available via Composer 👍

**Comment by CasperSiew15** [comment]
Hi.
May I check can I change font color to other color? and add border?
