### ISSUE TITLE
 stream_socket_client() open with fail

### ISSUE THREAD

**Issue by Anastasia-Gorobets** [RamyTalal/Label-Printer#2]
I try to use example:
`$stream = stream_socket_client("'tcp://192.168.1.8:9100", $errno, $errstr);
`

But I got error:
Warning: stream_socket_client(): php_network_getaddresses: getaddrinfo failed
Warning: stream_socket_client(): unable to connect to \'tcp://192.168.1.8:9100 (php_network_getaddresses: getaddrinfo failed) 

How can I fix it? Thanks.

**Comment by RamyTalal** [comment]
Is that IP address accessible?

**Comment by Anastasia-Gorobets** [comment]
@RamyTalal  no, ip address is not accessible 
I dont understand what this ip address mean and where can I get correct value? Thanks

**Comment by RamyTalal** [comment]
You can get the IP address in the setup process of the printer. Check the manual of the device for more information.

**Comment by Anastasia-Gorobets** [comment]
@RamyTalal  thanks 
One more question: maybe you know any sources for virtual testing Brother QL-720NW ( if I dont have Brother QL-720NW but need develop for it)? Thanks.

**Comment by RamyTalal** [comment]
No, not that I'm aware of.

I'll close this issue for now.
