### ISSUE TITLE
Landscape mode

### ISSUE THREAD

**Issue by ubay25** [RamyTalal/Label-Printer#20]
@RamyTalal is there an option for a landscape mode? Thanks!

**Comment by RamyTalal** [comment]
I think it's the Rotate command (not entirely sure). https://github.com/RamyTalal/Label-Printer/blob/master/src/Command/Rotate.php

**Comment by ubay25** [comment]
@RamyTalal thanks! It worked but the settings on character sizes, alignments, etc. were ignored.

**Comment by ntaylor-86** [comment]
@ubay25 I think you have to set the orientation first then apply your format settings.
Give that a shot.

**Comment by ntaylor-86** [comment]
Just reading the ESC/P Command Reference...

**Description**

* Using this command clears all text. 
* Before entering text, specify the paper orientation with this command. 
* When the printer is turned on, the landscape orientation is canceled.

**Comment by RamyTalal** [comment]
@ubay25 See @ntaylor-86's comment. I'll close this issue for now.
