### ISSUE TITLE
Fatal error: Class 'Talal\LabelPrinter\Printer' not found

### ISSUE THREAD

**Issue by malikmani** [RamyTalal/Label-Printer#3]
I am trying to connect to a remote printer using your library. However, I am having issues in configuration the library. I followed the steps the according the readme file.

**Fatal error: Class 'Talal\LabelPrinter\Printer' not found in /Applications/AMPPS/www/test-lol/test.php on line 9**

Can you please help me what I have to do in order to resolve the issue?

**Comment by RamyTalal** [comment]
Do you have
```php
require_once 'vendor/autoload.php';
```

at the top of your code?

**Comment by malikmani** [comment]
Adding the 'vendor/autoload.php' on top of my code resolved the issue. However, it's seems to be not printing the label. Also can you please me let me that is it possible to print the label using IPP port if printer is accessible from another remote network?

**Comment by RamyTalal** [comment]
I think it's possible, see http://lmgtfy.com/?q=php+ipp

**Comment by malikmani** [comment]
Thanks @RamyTalal I will look into this library.
