### ISSUE TITLE
It is possible to return command instead of sending to print?

### ISSUE THREAD

**Issue by iKarl** [RamyTalal/Label-Printer#40]
Hello, Before continuing, I would like to tell you that this is an excellent library and it works perfectly with the QL-1110NWB!!!

**Thank you very much for your time and for this development!**

Continuing with my question, can a method be made that instead of sending the command to print, it returns it in a chain so that it can be sent through another type of connection, such as Bluetooth for example?

Once again, many, many thanks for sharing this excellent development!

So sorry for my english.

**Comment by ntaylor-86** [comment]
Hi iKarl,

To returns the commands instead of sending to print, you can use the getCommands() on the mode class.

e.g.

```php
$stream = fopen('php://temp', 'rw');
$printer = new Printer(new Escp($stream));
$font = new Command\Font('brussels', Command\Font::TYPE_OUTLINE);
$printer->addCommand(new Command\CharStyle(Command\CharStyle::NORMAL));
$printer->addCommand($font);
$printer->addCommand(new Command\CharSize(46, $font));
$printer->addCommand(new Command\Align(Command\Align::CENTER));
$printer->addCommand(new Command\Text('Hallo'));

$commands = $printer->getMode()->getCommands();
```

**Comment by iKarl** [comment]
Hi ntaylor,

It's so true, thank you very much.

Regards

**Comment by ntaylor-86** [comment]
@RamyTalal do you want to close this issue off?
