### ISSUE TITLE
usb printer

### ISSUE THREAD

**Issue by davidgabbay** [RamyTalal/Label-Printer#7]
what should i do if i connect the printer to a USB port. 
What should i put in this line:
$stream = stream_socket_client('tcp://192.168.1.8:9100', $errorNumber, $errorString);

**Comment by RamyTalal** [comment]
I'm not really sure how to do it. Have you tried a Google search?

**Comment by davidgabbay** [comment]
Yes I did, I might have to buy the network printer rather than the QL-570 which is not.

Thanks anyhow

**Comment by RamyTalal** [comment]
@davidgabbay I've only tested the library with the QL-720NW.
