### ISSUE TITLE
Fatal error: Cannot use 'Object' as class name as it is reserved in /vendor/ramytalal/label-printer/src/Command/Object.php

### ISSUE THREAD

**Issue by daanj1998** [RamyTalal/Label-Printer#9]
I get the following error running the example script to print the template with some variables:

`Fatal error: Cannot use 'Object' as class name as it is reserved in /vendor/ramytalal/label-printer/src/Command/Object.php`

This is because the class Object is a reserved keyword in PHP 7.2 and above. So my suggestion is to rename this class to another one.

**Comment by RamyTalal** [comment]
Done! Thanks for reporting!
